			/*COMMUNITY*/
insert into Community (YardID, Name) values (1, 'Blue Quill');
insert into Community (YardID, Name) values (1, 'Heritage');
insert into Community (YardID, Name) values (1, 'Ambleside');
insert into Community (YardID, Name) values (1, 'Steel Hight');
insert into Community (YardID, Name) values (1, 'Margrath');
insert into Community (YardID, Name) values (1, 'Bonnie Doon');
insert into Community (YardID, Name) values (1, 'Charlesworth');
insert into Community (YardID, Name) values (1, 'Cloverdale');
insert into Community (YardID, Name) values (1, 'Ellerslie');
insert into Community (YardID, Name) values (1, 'Collin wood');
insert into Community (YardID, Name) values (1, 'Avonmore');
insert into Community (YardID, Name) values (1, 'McEwan');
insert into Community (YardID, Name) values (1, 'Beacon Height');
insert into Community (YardID, Name) values (1, 'South Park');
insert into Community (YardID, Name) values (1, 'Glenridding');
insert into Community (YardID, Name) values (1, 'Allard');
insert into Community (YardID, Name) values (1, 'Buleya');
insert into Community (YardID, Name) values (1, 'Twin Brooks');
insert into Community (YardID, Name) values (1, 'Hermitage');
insert into Community (YardID, Name) values (1, 'Landcaster');
insert into Community (YardID, Name) values (1, 'Victoria Heights');